name: Actions
on: workflow_dispach:
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: Hello from GHA
        run: echo Hello from GHA action.yml
      - name: GH CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --title "The bug is fixed" --body "Everything works again"
