name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: stage
      url: https://github.com
    steps:
      - name: deploy
        run: echo My secret is ${{ secrets.PASS }}
