name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: stage
      url: https://viktor.com
    steps:
      - name: deploy
        run: |
          MY_SEC=$(${{ secrets.PASS }} | base64)
          SHOWIT=$(echo $MY_SEC | base64 --decode)
          echo LET US LOOK on $SHOWIT 
      - name: Get object
        run: |
          echo "${{ toJSON(github) }}"
