name: Hello world

on: push

jobs:
  say:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo Hello from GHA repository
      - name: Checkout
        uses: actions/checkout@v3.5.3     
      - name: GH CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --base second --title "The bug is fixed" --body "Everything works again"
