name: Hello world

on: push

jobs:
  say:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Say hello
        run: echo Hello from GHA repository
      - name: Checkout
        uses: actions/checkout@v3.5.3     
      - name: GH CLI
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          gh repo list
          gh pr create --title "The bug is fixed" --body "Everything works again" --base second
