name: Manual test

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  first:
    runs-on: [self-hosted, docker]
    steps:
      - name: Hello
        run: echo Hello; sleep10
  second:
    runs-on: [self-hosted, docker]
    steps:
      - name: Hello
        run: echo Hello second; sleep10
  third:
    runs-on: [self-hosted, docker]
    steps:
      - name: Hello
        run: echo Hello third; sleep10        
