name: Manual test

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  first:
    runs-on: [self-hosted, docker]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Hello
        run: |          
          ln -s ../../../_common_workspace ws  
          echo "" >> ws/README.md
          echo "FIRTST JOB" >> ws/README.md
          ls -l ws
  second:
    needs: first
    runs-on: [self-hosted, docker]
    steps:
      - name: Hello
        run: | 
          ln -s ../../../_common_workspace ws
          pwd
          ls -l
          ls -l ws
  third:
    needs: first
    runs-on: [self-hosted, docker]
    steps:
      - name: Hello
        run: | 
          ln -s ../../../_common_workspace ws
          pwd
          ls -l
          ls -l ws
