name: Manual test

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  first:
    runs-on: [self-hosted, docker]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Hello
        run: |          
          pwd
          ls -l
          echo "" >> README.md
          echo "FIRTST JOB" >> README.md
          echo '========================='
          cat README.md
          echo '========================='
  second:
    needs: first
    runs-on: [self-hosted, docker]
    steps:
      - name: Hello
        run: |  
          pwd
          ls -l
          echo '========================='
          echo "SECOND JOB" >> README.md
          cat README.md
          echo '========================='
          cd ../../
          mkdir -p new
          echo "LINE" >> new/file1
          pwd
          ll
  third:
    needs: first
    runs-on: [self-hosted, docker]
    steps:
      - name: Hello
        run: | 
          pwd
          ls -l
          echo '========================='
          echo "THIRD JOB" >> README.md
          cat README.md  
          echo '========================='
