name: Manual test

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  first:
    runs-on: [self-hosted, docker]
    steps:
      - name: Hello
        run: echo Hello; sleep 100
  second:
    runs-on: [self-hosted, docker]
    steps:
      - name: Hello
        run: echo Hello second; sleep 100
  third:
    runs-on: [self-hosted, docker]
    steps:
      - name: Hello
        run: echo Hello third; sleep 100        
