name: Manual test

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  first:
    runs-on: [self-hosted, docker]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Hello
        run: |
          echo Hello
          sleep 3
          ls ../ -l
          mkdir NEW1
          ls ../ -l
          cat README.md
          echo "FIRTST JOB" >> README.md
          cat README.md
  second:
    needs: first
    runs-on: [self-hosted, docker]
    steps:
      - name: Hello
        run: |
          echo Hello
          sleep 3
          ls ../ -l
          mkdir NEW2
          ls ../ -l
          cat README.md
          echo "SECOND JOB" >> README.md
          cat README.md
  third:
    needs: first
    runs-on: [self-hosted, docker]
    steps:
      - name: Hello
        run: |
          echo Hello
          sleep 3
          ls ../ -l
          mkdir NEW3
          ls ../ -l
          cat README.md
          echo "THIRD JOB" >> README.md
          cat README.md       
